source("https://raw.githubusercontent.com/timriffe/covid_age/master/R/00_Functions.R")

setwd(wd_sched_detect())
here::i_am("covid_age.Rproj")
startup::startup()
getwd()
here()
# here::i_am(file.path(wd_sched_detect(), "covid_age.Rproj"))
# getwd()
# change_here(wd_sched_detect())
# getwd()
# setwd(wd_sched_detect())
# getwd()
# here()